// Thin wrapper around the Xilinx HBM IP with an integrated M1 smoke-test
// traffic generator.
//
// HBM IP (PG276 / Vivado 2025.2) requires:
//  - IBUFDS for differential ref clock (IP takes single-ended HBM_REF_CLK_x)
//  - APB clocks/resets for both stacks (required for internal init sequence)
//  - All 32 AXI port clocks driven (even unused ports — optimizer constraint)
//  - AXI IDs are 6-bit and burst lengths are 4-bit (AXI3-like, max 16 beats)
`timescale 1ns/1ps
/* verilator lint_off UNUSEDSIGNAL */
module hbm_wrapper (
  // HBM reference clock (differential, 100 MHz)
  input  wire  hbm_refclk_p,
  input  wire  hbm_refclk_n,
  // User-domain clock and active-high reset (250 MHz, from XDMA)
  input  wire  user_clk,
  input  wire  user_rstn,
  // Smoke-test control (from BAR0 CONTROL[4])
  input  logic smoke_go,
  output logic smoke_done,
  output logic smoke_any_error,
  // HBM calibration / ready status
  output wire  hbm_ready
);

  // -------------------------------------------------------------------------
  // HBM reference clock: convert differential pair to single-ended
  // HBM_REF_CLK_0/1 inputs on the IP are single-ended (IBUFDS is external)
  // -------------------------------------------------------------------------
  wire hbm_ref_clk;
  IBUFDS u_ibufds_hbm (
    .I  (hbm_refclk_p),
    .IB (hbm_refclk_n),
    .O  (hbm_ref_clk)
  );

  // -------------------------------------------------------------------------
  // AXI widths as generated by the HBM IP (PG276 Table 2-11)
  // -------------------------------------------------------------------------
  localparam int AXI_DATA_W = 256;
  localparam int AXI_ADDR_W = 33;
  localparam int AXI_ID_W   = 6;   // HBM uses 6-bit IDs
  localparam int AXI_LEN_W  = 4;   // max 16-beat bursts (4-bit length field)

  // -------------------------------------------------------------------------
  // Internal AXI wires: traffic generator uses 8-bit IDs and 8-bit lengths;
  // width adaptation occurs at the HBM port connections below.
  // -------------------------------------------------------------------------
  logic [7:0]              tg_awid;
  logic [AXI_ADDR_W-1:0]  tg_awaddr;
  logic [7:0]              tg_awlen;
  logic [2:0]              tg_awsize;
  logic [1:0]              tg_awburst;
  logic                    tg_awvalid;
  logic                    tg_awready;
  logic [AXI_DATA_W-1:0]  tg_wdata;
  logic [AXI_DATA_W/8-1:0] tg_wstrb;
  logic                    tg_wlast;
  logic                    tg_wvalid;
  logic                    tg_wready;
  wire  [AXI_ID_W-1:0]    hbm_bid;
  logic [1:0]              tg_bresp;
  logic                    tg_bvalid;
  logic                    tg_bready;
  logic [7:0]              tg_arid;
  logic [AXI_ADDR_W-1:0]  tg_araddr;
  logic [7:0]              tg_arlen;
  logic [2:0]              tg_arsize;
  logic [1:0]              tg_arburst;
  logic                    tg_arvalid;
  logic                    tg_arready;
  wire  [AXI_ID_W-1:0]    hbm_rid;
  logic [AXI_DATA_W-1:0]  tg_rdata;
  logic [1:0]              tg_rresp;
  logic                    tg_rlast;
  logic                    tg_rvalid;
  logic                    tg_rready;

  // Zero-extend 6-bit HBM IDs to 8-bit TG ports
  logic [7:0] tg_bid, tg_rid;
  assign tg_bid = {2'b0, hbm_bid};
  assign tg_rid = {2'b0, hbm_rid};

  logic [31:0] tg_axi_errors;
  logic [31:0] tg_data_mismatches;
  logic        tg_done;

  always_ff @(posedge user_clk or negedge user_rstn) begin
    if (!user_rstn) begin
      smoke_done      <= 1'b0;
      smoke_any_error <= 1'b0;
    end else begin
      smoke_done      <= tg_done;
      smoke_any_error <= tg_done && ((tg_axi_errors != '0) || (tg_data_mismatches != '0));
    end
  end

  // -------------------------------------------------------------------------
  // Traffic generator: 16 MB write + readback
  // -------------------------------------------------------------------------
  hbm_traffic_gen #(
    .AXI_DATA_W (AXI_DATA_W),
    .AXI_ADDR_W (AXI_ADDR_W),
    .BURST_LEN  (16)
  ) u_tg (
    .clk             (user_clk),
    .rstn            (user_rstn),
    .start           (smoke_go),
    .num_bytes       (32'd16_777_216),
    .done            (tg_done),
    .axi_errors      (tg_axi_errors),
    .data_mismatches (tg_data_mismatches),
    .m_axi_awid      (tg_awid),
    .m_axi_awaddr    (tg_awaddr),
    .m_axi_awlen     (tg_awlen),
    .m_axi_awsize    (tg_awsize),
    .m_axi_awburst   (tg_awburst),
    .m_axi_awvalid   (tg_awvalid),
    .m_axi_awready   (tg_awready),
    .m_axi_wdata     (tg_wdata),
    .m_axi_wstrb     (tg_wstrb),
    .m_axi_wlast     (tg_wlast),
    .m_axi_wvalid    (tg_wvalid),
    .m_axi_wready    (tg_wready),
    .m_axi_bid       (tg_bid),
    .m_axi_bresp     (tg_bresp),
    .m_axi_bvalid    (tg_bvalid),
    .m_axi_bready    (tg_bready),
    .m_axi_arid      (tg_arid),
    .m_axi_araddr    (tg_araddr),
    .m_axi_arlen     (tg_arlen),
    .m_axi_arsize    (tg_arsize),
    .m_axi_arburst   (tg_arburst),
    .m_axi_arvalid   (tg_arvalid),
    .m_axi_arready   (tg_arready),
    .m_axi_rid       (tg_rid),
    .m_axi_rdata     (tg_rdata),
    .m_axi_rresp     (tg_rresp),
    .m_axi_rlast     (tg_rlast),
    .m_axi_rvalid    (tg_rvalid),
    .m_axi_rready    (tg_rready)
  );

  // -------------------------------------------------------------------------
  // HBM IP instantiation
  // -------------------------------------------------------------------------
  logic apb_complete_0;
  logic apb_complete_1;
  assign hbm_ready = apb_complete_0 & apb_complete_1;

  /* verilator lint_off PINCONNECTEMPTY */
  hbm u_hbm (
    // Reference clocks: both stacks share the same 100 MHz single-ended clock
    .HBM_REF_CLK_0     (hbm_ref_clk),
    .HBM_REF_CLK_1     (hbm_ref_clk),

    // APB — stack 0: tied off (HBM initializes autonomously via internal FSM)
    .APB_0_PWDATA      (32'd0),
    .APB_0_PADDR       (22'd0),
    .APB_0_PCLK        (hbm_ref_clk),
    .APB_0_PENABLE     (1'b0),
    .APB_0_PRESET_N    (1'b1),
    .APB_0_PSEL        (1'b0),
    .APB_0_PWRITE      (1'b0),
    .APB_0_PRDATA      (),
    .APB_0_PREADY      (),
    .APB_0_PSLVERR     (),

    // APB — stack 1
    .APB_1_PWDATA      (32'd0),
    .APB_1_PADDR       (22'd0),
    .APB_1_PCLK        (hbm_ref_clk),
    .APB_1_PENABLE     (1'b0),
    .APB_1_PRESET_N    (1'b1),
    .APB_1_PSEL        (1'b0),
    .APB_1_PWRITE      (1'b0),
    .APB_1_PRDATA      (),
    .APB_1_PREADY      (),
    .APB_1_PSLVERR     (),

    // AXI_00 — traffic generator (only enabled port)
    .AXI_00_ACLK       (user_clk),
    .AXI_00_ARESET_N   (user_rstn),
    .AXI_00_AWID       (tg_awid[AXI_ID_W-1:0]),
    .AXI_00_AWADDR     (tg_awaddr),
    .AXI_00_AWLEN      (tg_awlen[AXI_LEN_W-1:0]),
    .AXI_00_AWSIZE     (tg_awsize),
    .AXI_00_AWBURST    (tg_awburst),
    .AXI_00_AWVALID    (tg_awvalid),
    .AXI_00_AWREADY    (tg_awready),
    .AXI_00_WDATA      (tg_wdata),
    .AXI_00_WSTRB      (tg_wstrb),
    .AXI_00_WLAST      (tg_wlast),
    .AXI_00_WVALID     (tg_wvalid),
    .AXI_00_WREADY     (tg_wready),
    .AXI_00_WDATA_PARITY(32'd0),
    .AXI_00_BID        (hbm_bid),
    .AXI_00_BRESP      (tg_bresp),
    .AXI_00_BVALID     (tg_bvalid),
    .AXI_00_BREADY     (tg_bready),
    .AXI_00_ARID       (tg_arid[AXI_ID_W-1:0]),
    .AXI_00_ARADDR     (tg_araddr),
    .AXI_00_ARLEN      (tg_arlen[AXI_LEN_W-1:0]),
    .AXI_00_ARSIZE     (tg_arsize),
    .AXI_00_ARBURST    (tg_arburst),
    .AXI_00_ARVALID    (tg_arvalid),
    .AXI_00_ARREADY    (tg_arready),
    .AXI_00_RID        (hbm_rid),
    .AXI_00_RDATA      (tg_rdata),
    .AXI_00_RRESP      (tg_rresp),
    .AXI_00_RLAST      (tg_rlast),
    .AXI_00_RVALID     (tg_rvalid),
    .AXI_00_RREADY     (tg_rready),
    .AXI_00_RDATA_PARITY(),

    // AXI_01 through AXI_1F — unused ports, clocks driven to prevent dangling LUTs
    .AXI_01_ACLK(user_clk), .AXI_01_ARESET_N(1'b0),
    .AXI_01_AWID('0), .AXI_01_AWADDR('0), .AXI_01_AWLEN('0), .AXI_01_AWSIZE('0),
    .AXI_01_AWBURST('0), .AXI_01_AWVALID(1'b0), .AXI_01_AWREADY(),
    .AXI_01_WDATA('0), .AXI_01_WSTRB('0), .AXI_01_WLAST(1'b0), .AXI_01_WVALID(1'b0),
    .AXI_01_WREADY(), .AXI_01_WDATA_PARITY('0),
    .AXI_01_BID(), .AXI_01_BRESP(), .AXI_01_BVALID(), .AXI_01_BREADY(1'b0),
    .AXI_01_ARID('0), .AXI_01_ARADDR('0), .AXI_01_ARLEN('0), .AXI_01_ARSIZE('0),
    .AXI_01_ARBURST('0), .AXI_01_ARVALID(1'b0), .AXI_01_ARREADY(),
    .AXI_01_RID(), .AXI_01_RDATA(), .AXI_01_RRESP(), .AXI_01_RLAST(),
    .AXI_01_RVALID(), .AXI_01_RREADY(1'b0), .AXI_01_RDATA_PARITY(),

    .AXI_02_ACLK(user_clk), .AXI_02_ARESET_N(1'b0),
    .AXI_02_AWID('0), .AXI_02_AWADDR('0), .AXI_02_AWLEN('0), .AXI_02_AWSIZE('0),
    .AXI_02_AWBURST('0), .AXI_02_AWVALID(1'b0), .AXI_02_AWREADY(),
    .AXI_02_WDATA('0), .AXI_02_WSTRB('0), .AXI_02_WLAST(1'b0), .AXI_02_WVALID(1'b0),
    .AXI_02_WREADY(), .AXI_02_WDATA_PARITY('0),
    .AXI_02_BID(), .AXI_02_BRESP(), .AXI_02_BVALID(), .AXI_02_BREADY(1'b0),
    .AXI_02_ARID('0), .AXI_02_ARADDR('0), .AXI_02_ARLEN('0), .AXI_02_ARSIZE('0),
    .AXI_02_ARBURST('0), .AXI_02_ARVALID(1'b0), .AXI_02_ARREADY(),
    .AXI_02_RID(), .AXI_02_RDATA(), .AXI_02_RRESP(), .AXI_02_RLAST(),
    .AXI_02_RVALID(), .AXI_02_RREADY(1'b0), .AXI_02_RDATA_PARITY(),

    .AXI_03_ACLK(user_clk), .AXI_03_ARESET_N(1'b0),
    .AXI_03_AWID('0), .AXI_03_AWADDR('0), .AXI_03_AWLEN('0), .AXI_03_AWSIZE('0),
    .AXI_03_AWBURST('0), .AXI_03_AWVALID(1'b0), .AXI_03_AWREADY(),
    .AXI_03_WDATA('0), .AXI_03_WSTRB('0), .AXI_03_WLAST(1'b0), .AXI_03_WVALID(1'b0),
    .AXI_03_WREADY(), .AXI_03_WDATA_PARITY('0),
    .AXI_03_BID(), .AXI_03_BRESP(), .AXI_03_BVALID(), .AXI_03_BREADY(1'b0),
    .AXI_03_ARID('0), .AXI_03_ARADDR('0), .AXI_03_ARLEN('0), .AXI_03_ARSIZE('0),
    .AXI_03_ARBURST('0), .AXI_03_ARVALID(1'b0), .AXI_03_ARREADY(),
    .AXI_03_RID(), .AXI_03_RDATA(), .AXI_03_RRESP(), .AXI_03_RLAST(),
    .AXI_03_RVALID(), .AXI_03_RREADY(1'b0), .AXI_03_RDATA_PARITY(),

    .AXI_04_ACLK(user_clk), .AXI_04_ARESET_N(1'b0),
    .AXI_04_AWID('0), .AXI_04_AWADDR('0), .AXI_04_AWLEN('0), .AXI_04_AWSIZE('0),
    .AXI_04_AWBURST('0), .AXI_04_AWVALID(1'b0), .AXI_04_AWREADY(),
    .AXI_04_WDATA('0), .AXI_04_WSTRB('0), .AXI_04_WLAST(1'b0), .AXI_04_WVALID(1'b0),
    .AXI_04_WREADY(), .AXI_04_WDATA_PARITY('0),
    .AXI_04_BID(), .AXI_04_BRESP(), .AXI_04_BVALID(), .AXI_04_BREADY(1'b0),
    .AXI_04_ARID('0), .AXI_04_ARADDR('0), .AXI_04_ARLEN('0), .AXI_04_ARSIZE('0),
    .AXI_04_ARBURST('0), .AXI_04_ARVALID(1'b0), .AXI_04_ARREADY(),
    .AXI_04_RID(), .AXI_04_RDATA(), .AXI_04_RRESP(), .AXI_04_RLAST(),
    .AXI_04_RVALID(), .AXI_04_RREADY(1'b0), .AXI_04_RDATA_PARITY(),

    .AXI_05_ACLK(user_clk), .AXI_05_ARESET_N(1'b0),
    .AXI_05_AWID('0), .AXI_05_AWADDR('0), .AXI_05_AWLEN('0), .AXI_05_AWSIZE('0),
    .AXI_05_AWBURST('0), .AXI_05_AWVALID(1'b0), .AXI_05_AWREADY(),
    .AXI_05_WDATA('0), .AXI_05_WSTRB('0), .AXI_05_WLAST(1'b0), .AXI_05_WVALID(1'b0),
    .AXI_05_WREADY(), .AXI_05_WDATA_PARITY('0),
    .AXI_05_BID(), .AXI_05_BRESP(), .AXI_05_BVALID(), .AXI_05_BREADY(1'b0),
    .AXI_05_ARID('0), .AXI_05_ARADDR('0), .AXI_05_ARLEN('0), .AXI_05_ARSIZE('0),
    .AXI_05_ARBURST('0), .AXI_05_ARVALID(1'b0), .AXI_05_ARREADY(),
    .AXI_05_RID(), .AXI_05_RDATA(), .AXI_05_RRESP(), .AXI_05_RLAST(),
    .AXI_05_RVALID(), .AXI_05_RREADY(1'b0), .AXI_05_RDATA_PARITY(),

    .AXI_06_ACLK(user_clk), .AXI_06_ARESET_N(1'b0),
    .AXI_06_AWID('0), .AXI_06_AWADDR('0), .AXI_06_AWLEN('0), .AXI_06_AWSIZE('0),
    .AXI_06_AWBURST('0), .AXI_06_AWVALID(1'b0), .AXI_06_AWREADY(),
    .AXI_06_WDATA('0), .AXI_06_WSTRB('0), .AXI_06_WLAST(1'b0), .AXI_06_WVALID(1'b0),
    .AXI_06_WREADY(), .AXI_06_WDATA_PARITY('0),
    .AXI_06_BID(), .AXI_06_BRESP(), .AXI_06_BVALID(), .AXI_06_BREADY(1'b0),
    .AXI_06_ARID('0), .AXI_06_ARADDR('0), .AXI_06_ARLEN('0), .AXI_06_ARSIZE('0),
    .AXI_06_ARBURST('0), .AXI_06_ARVALID(1'b0), .AXI_06_ARREADY(),
    .AXI_06_RID(), .AXI_06_RDATA(), .AXI_06_RRESP(), .AXI_06_RLAST(),
    .AXI_06_RVALID(), .AXI_06_RREADY(1'b0), .AXI_06_RDATA_PARITY(),

    .AXI_07_ACLK(user_clk), .AXI_07_ARESET_N(1'b0),
    .AXI_07_AWID('0), .AXI_07_AWADDR('0), .AXI_07_AWLEN('0), .AXI_07_AWSIZE('0),
    .AXI_07_AWBURST('0), .AXI_07_AWVALID(1'b0), .AXI_07_AWREADY(),
    .AXI_07_WDATA('0), .AXI_07_WSTRB('0), .AXI_07_WLAST(1'b0), .AXI_07_WVALID(1'b0),
    .AXI_07_WREADY(), .AXI_07_WDATA_PARITY('0),
    .AXI_07_BID(), .AXI_07_BRESP(), .AXI_07_BVALID(), .AXI_07_BREADY(1'b0),
    .AXI_07_ARID('0), .AXI_07_ARADDR('0), .AXI_07_ARLEN('0), .AXI_07_ARSIZE('0),
    .AXI_07_ARBURST('0), .AXI_07_ARVALID(1'b0), .AXI_07_ARREADY(),
    .AXI_07_RID(), .AXI_07_RDATA(), .AXI_07_RRESP(), .AXI_07_RLAST(),
    .AXI_07_RVALID(), .AXI_07_RREADY(1'b0), .AXI_07_RDATA_PARITY(),

    .AXI_08_ACLK(user_clk), .AXI_08_ARESET_N(1'b0),
    .AXI_08_AWID('0), .AXI_08_AWADDR('0), .AXI_08_AWLEN('0), .AXI_08_AWSIZE('0),
    .AXI_08_AWBURST('0), .AXI_08_AWVALID(1'b0), .AXI_08_AWREADY(),
    .AXI_08_WDATA('0), .AXI_08_WSTRB('0), .AXI_08_WLAST(1'b0), .AXI_08_WVALID(1'b0),
    .AXI_08_WREADY(), .AXI_08_WDATA_PARITY('0),
    .AXI_08_BID(), .AXI_08_BRESP(), .AXI_08_BVALID(), .AXI_08_BREADY(1'b0),
    .AXI_08_ARID('0), .AXI_08_ARADDR('0), .AXI_08_ARLEN('0), .AXI_08_ARSIZE('0),
    .AXI_08_ARBURST('0), .AXI_08_ARVALID(1'b0), .AXI_08_ARREADY(),
    .AXI_08_RID(), .AXI_08_RDATA(), .AXI_08_RRESP(), .AXI_08_RLAST(),
    .AXI_08_RVALID(), .AXI_08_RREADY(1'b0), .AXI_08_RDATA_PARITY(),

    .AXI_09_ACLK(user_clk), .AXI_09_ARESET_N(1'b0),
    .AXI_09_AWID('0), .AXI_09_AWADDR('0), .AXI_09_AWLEN('0), .AXI_09_AWSIZE('0),
    .AXI_09_AWBURST('0), .AXI_09_AWVALID(1'b0), .AXI_09_AWREADY(),
    .AXI_09_WDATA('0), .AXI_09_WSTRB('0), .AXI_09_WLAST(1'b0), .AXI_09_WVALID(1'b0),
    .AXI_09_WREADY(), .AXI_09_WDATA_PARITY('0),
    .AXI_09_BID(), .AXI_09_BRESP(), .AXI_09_BVALID(), .AXI_09_BREADY(1'b0),
    .AXI_09_ARID('0), .AXI_09_ARADDR('0), .AXI_09_ARLEN('0), .AXI_09_ARSIZE('0),
    .AXI_09_ARBURST('0), .AXI_09_ARVALID(1'b0), .AXI_09_ARREADY(),
    .AXI_09_RID(), .AXI_09_RDATA(), .AXI_09_RRESP(), .AXI_09_RLAST(),
    .AXI_09_RVALID(), .AXI_09_RREADY(1'b0), .AXI_09_RDATA_PARITY(),

    .AXI_10_ACLK(user_clk), .AXI_10_ARESET_N(1'b0),
    .AXI_10_AWID('0), .AXI_10_AWADDR('0), .AXI_10_AWLEN('0), .AXI_10_AWSIZE('0),
    .AXI_10_AWBURST('0), .AXI_10_AWVALID(1'b0), .AXI_10_AWREADY(),
    .AXI_10_WDATA('0), .AXI_10_WSTRB('0), .AXI_10_WLAST(1'b0), .AXI_10_WVALID(1'b0),
    .AXI_10_WREADY(), .AXI_10_WDATA_PARITY('0),
    .AXI_10_BID(), .AXI_10_BRESP(), .AXI_10_BVALID(), .AXI_10_BREADY(1'b0),
    .AXI_10_ARID('0), .AXI_10_ARADDR('0), .AXI_10_ARLEN('0), .AXI_10_ARSIZE('0),
    .AXI_10_ARBURST('0), .AXI_10_ARVALID(1'b0), .AXI_10_ARREADY(),
    .AXI_10_RID(), .AXI_10_RDATA(), .AXI_10_RRESP(), .AXI_10_RLAST(),
    .AXI_10_RVALID(), .AXI_10_RREADY(1'b0), .AXI_10_RDATA_PARITY(),

    .AXI_11_ACLK(user_clk), .AXI_11_ARESET_N(1'b0),
    .AXI_11_AWID('0), .AXI_11_AWADDR('0), .AXI_11_AWLEN('0), .AXI_11_AWSIZE('0),
    .AXI_11_AWBURST('0), .AXI_11_AWVALID(1'b0), .AXI_11_AWREADY(),
    .AXI_11_WDATA('0), .AXI_11_WSTRB('0), .AXI_11_WLAST(1'b0), .AXI_11_WVALID(1'b0),
    .AXI_11_WREADY(), .AXI_11_WDATA_PARITY('0),
    .AXI_11_BID(), .AXI_11_BRESP(), .AXI_11_BVALID(), .AXI_11_BREADY(1'b0),
    .AXI_11_ARID('0), .AXI_11_ARADDR('0), .AXI_11_ARLEN('0), .AXI_11_ARSIZE('0),
    .AXI_11_ARBURST('0), .AXI_11_ARVALID(1'b0), .AXI_11_ARREADY(),
    .AXI_11_RID(), .AXI_11_RDATA(), .AXI_11_RRESP(), .AXI_11_RLAST(),
    .AXI_11_RVALID(), .AXI_11_RREADY(1'b0), .AXI_11_RDATA_PARITY(),

    .AXI_12_ACLK(user_clk), .AXI_12_ARESET_N(1'b0),
    .AXI_12_AWID('0), .AXI_12_AWADDR('0), .AXI_12_AWLEN('0), .AXI_12_AWSIZE('0),
    .AXI_12_AWBURST('0), .AXI_12_AWVALID(1'b0), .AXI_12_AWREADY(),
    .AXI_12_WDATA('0), .AXI_12_WSTRB('0), .AXI_12_WLAST(1'b0), .AXI_12_WVALID(1'b0),
    .AXI_12_WREADY(), .AXI_12_WDATA_PARITY('0),
    .AXI_12_BID(), .AXI_12_BRESP(), .AXI_12_BVALID(), .AXI_12_BREADY(1'b0),
    .AXI_12_ARID('0), .AXI_12_ARADDR('0), .AXI_12_ARLEN('0), .AXI_12_ARSIZE('0),
    .AXI_12_ARBURST('0), .AXI_12_ARVALID(1'b0), .AXI_12_ARREADY(),
    .AXI_12_RID(), .AXI_12_RDATA(), .AXI_12_RRESP(), .AXI_12_RLAST(),
    .AXI_12_RVALID(), .AXI_12_RREADY(1'b0), .AXI_12_RDATA_PARITY(),

    .AXI_13_ACLK(user_clk), .AXI_13_ARESET_N(1'b0),
    .AXI_13_AWID('0), .AXI_13_AWADDR('0), .AXI_13_AWLEN('0), .AXI_13_AWSIZE('0),
    .AXI_13_AWBURST('0), .AXI_13_AWVALID(1'b0), .AXI_13_AWREADY(),
    .AXI_13_WDATA('0), .AXI_13_WSTRB('0), .AXI_13_WLAST(1'b0), .AXI_13_WVALID(1'b0),
    .AXI_13_WREADY(), .AXI_13_WDATA_PARITY('0),
    .AXI_13_BID(), .AXI_13_BRESP(), .AXI_13_BVALID(), .AXI_13_BREADY(1'b0),
    .AXI_13_ARID('0), .AXI_13_ARADDR('0), .AXI_13_ARLEN('0), .AXI_13_ARSIZE('0),
    .AXI_13_ARBURST('0), .AXI_13_ARVALID(1'b0), .AXI_13_ARREADY(),
    .AXI_13_RID(), .AXI_13_RDATA(), .AXI_13_RRESP(), .AXI_13_RLAST(),
    .AXI_13_RVALID(), .AXI_13_RREADY(1'b0), .AXI_13_RDATA_PARITY(),

    .AXI_14_ACLK(user_clk), .AXI_14_ARESET_N(1'b0),
    .AXI_14_AWID('0), .AXI_14_AWADDR('0), .AXI_14_AWLEN('0), .AXI_14_AWSIZE('0),
    .AXI_14_AWBURST('0), .AXI_14_AWVALID(1'b0), .AXI_14_AWREADY(),
    .AXI_14_WDATA('0), .AXI_14_WSTRB('0), .AXI_14_WLAST(1'b0), .AXI_14_WVALID(1'b0),
    .AXI_14_WREADY(), .AXI_14_WDATA_PARITY('0),
    .AXI_14_BID(), .AXI_14_BRESP(), .AXI_14_BVALID(), .AXI_14_BREADY(1'b0),
    .AXI_14_ARID('0), .AXI_14_ARADDR('0), .AXI_14_ARLEN('0), .AXI_14_ARSIZE('0),
    .AXI_14_ARBURST('0), .AXI_14_ARVALID(1'b0), .AXI_14_ARREADY(),
    .AXI_14_RID(), .AXI_14_RDATA(), .AXI_14_RRESP(), .AXI_14_RLAST(),
    .AXI_14_RVALID(), .AXI_14_RREADY(1'b0), .AXI_14_RDATA_PARITY(),

    .AXI_15_ACLK(user_clk), .AXI_15_ARESET_N(1'b0),
    .AXI_15_AWID('0), .AXI_15_AWADDR('0), .AXI_15_AWLEN('0), .AXI_15_AWSIZE('0),
    .AXI_15_AWBURST('0), .AXI_15_AWVALID(1'b0), .AXI_15_AWREADY(),
    .AXI_15_WDATA('0), .AXI_15_WSTRB('0), .AXI_15_WLAST(1'b0), .AXI_15_WVALID(1'b0),
    .AXI_15_WREADY(), .AXI_15_WDATA_PARITY('0),
    .AXI_15_BID(), .AXI_15_BRESP(), .AXI_15_BVALID(), .AXI_15_BREADY(1'b0),
    .AXI_15_ARID('0), .AXI_15_ARADDR('0), .AXI_15_ARLEN('0), .AXI_15_ARSIZE('0),
    .AXI_15_ARBURST('0), .AXI_15_ARVALID(1'b0), .AXI_15_ARREADY(),
    .AXI_15_RID(), .AXI_15_RDATA(), .AXI_15_RRESP(), .AXI_15_RLAST(),
    .AXI_15_RVALID(), .AXI_15_RREADY(1'b0), .AXI_15_RDATA_PARITY(),

    .AXI_16_ACLK(user_clk), .AXI_16_ARESET_N(1'b0),
    .AXI_16_AWID('0), .AXI_16_AWADDR('0), .AXI_16_AWLEN('0), .AXI_16_AWSIZE('0),
    .AXI_16_AWBURST('0), .AXI_16_AWVALID(1'b0), .AXI_16_AWREADY(),
    .AXI_16_WDATA('0), .AXI_16_WSTRB('0), .AXI_16_WLAST(1'b0), .AXI_16_WVALID(1'b0),
    .AXI_16_WREADY(), .AXI_16_WDATA_PARITY('0),
    .AXI_16_BID(), .AXI_16_BRESP(), .AXI_16_BVALID(), .AXI_16_BREADY(1'b0),
    .AXI_16_ARID('0), .AXI_16_ARADDR('0), .AXI_16_ARLEN('0), .AXI_16_ARSIZE('0),
    .AXI_16_ARBURST('0), .AXI_16_ARVALID(1'b0), .AXI_16_ARREADY(),
    .AXI_16_RID(), .AXI_16_RDATA(), .AXI_16_RRESP(), .AXI_16_RLAST(),
    .AXI_16_RVALID(), .AXI_16_RREADY(1'b0), .AXI_16_RDATA_PARITY(),

    .AXI_17_ACLK(user_clk), .AXI_17_ARESET_N(1'b0),
    .AXI_17_AWID('0), .AXI_17_AWADDR('0), .AXI_17_AWLEN('0), .AXI_17_AWSIZE('0),
    .AXI_17_AWBURST('0), .AXI_17_AWVALID(1'b0), .AXI_17_AWREADY(),
    .AXI_17_WDATA('0), .AXI_17_WSTRB('0), .AXI_17_WLAST(1'b0), .AXI_17_WVALID(1'b0),
    .AXI_17_WREADY(), .AXI_17_WDATA_PARITY('0),
    .AXI_17_BID(), .AXI_17_BRESP(), .AXI_17_BVALID(), .AXI_17_BREADY(1'b0),
    .AXI_17_ARID('0), .AXI_17_ARADDR('0), .AXI_17_ARLEN('0), .AXI_17_ARSIZE('0),
    .AXI_17_ARBURST('0), .AXI_17_ARVALID(1'b0), .AXI_17_ARREADY(),
    .AXI_17_RID(), .AXI_17_RDATA(), .AXI_17_RRESP(), .AXI_17_RLAST(),
    .AXI_17_RVALID(), .AXI_17_RREADY(1'b0), .AXI_17_RDATA_PARITY(),

    .AXI_18_ACLK(user_clk), .AXI_18_ARESET_N(1'b0),
    .AXI_18_AWID('0), .AXI_18_AWADDR('0), .AXI_18_AWLEN('0), .AXI_18_AWSIZE('0),
    .AXI_18_AWBURST('0), .AXI_18_AWVALID(1'b0), .AXI_18_AWREADY(),
    .AXI_18_WDATA('0), .AXI_18_WSTRB('0), .AXI_18_WLAST(1'b0), .AXI_18_WVALID(1'b0),
    .AXI_18_WREADY(), .AXI_18_WDATA_PARITY('0),
    .AXI_18_BID(), .AXI_18_BRESP(), .AXI_18_BVALID(), .AXI_18_BREADY(1'b0),
    .AXI_18_ARID('0), .AXI_18_ARADDR('0), .AXI_18_ARLEN('0), .AXI_18_ARSIZE('0),
    .AXI_18_ARBURST('0), .AXI_18_ARVALID(1'b0), .AXI_18_ARREADY(),
    .AXI_18_RID(), .AXI_18_RDATA(), .AXI_18_RRESP(), .AXI_18_RLAST(),
    .AXI_18_RVALID(), .AXI_18_RREADY(1'b0), .AXI_18_RDATA_PARITY(),

    .AXI_19_ACLK(user_clk), .AXI_19_ARESET_N(1'b0),
    .AXI_19_AWID('0), .AXI_19_AWADDR('0), .AXI_19_AWLEN('0), .AXI_19_AWSIZE('0),
    .AXI_19_AWBURST('0), .AXI_19_AWVALID(1'b0), .AXI_19_AWREADY(),
    .AXI_19_WDATA('0), .AXI_19_WSTRB('0), .AXI_19_WLAST(1'b0), .AXI_19_WVALID(1'b0),
    .AXI_19_WREADY(), .AXI_19_WDATA_PARITY('0),
    .AXI_19_BID(), .AXI_19_BRESP(), .AXI_19_BVALID(), .AXI_19_BREADY(1'b0),
    .AXI_19_ARID('0), .AXI_19_ARADDR('0), .AXI_19_ARLEN('0), .AXI_19_ARSIZE('0),
    .AXI_19_ARBURST('0), .AXI_19_ARVALID(1'b0), .AXI_19_ARREADY(),
    .AXI_19_RID(), .AXI_19_RDATA(), .AXI_19_RRESP(), .AXI_19_RLAST(),
    .AXI_19_RVALID(), .AXI_19_RREADY(1'b0), .AXI_19_RDATA_PARITY(),

    .AXI_20_ACLK(user_clk), .AXI_20_ARESET_N(1'b0),
    .AXI_20_AWID('0), .AXI_20_AWADDR('0), .AXI_20_AWLEN('0), .AXI_20_AWSIZE('0),
    .AXI_20_AWBURST('0), .AXI_20_AWVALID(1'b0), .AXI_20_AWREADY(),
    .AXI_20_WDATA('0), .AXI_20_WSTRB('0), .AXI_20_WLAST(1'b0), .AXI_20_WVALID(1'b0),
    .AXI_20_WREADY(), .AXI_20_WDATA_PARITY('0),
    .AXI_20_BID(), .AXI_20_BRESP(), .AXI_20_BVALID(), .AXI_20_BREADY(1'b0),
    .AXI_20_ARID('0), .AXI_20_ARADDR('0), .AXI_20_ARLEN('0), .AXI_20_ARSIZE('0),
    .AXI_20_ARBURST('0), .AXI_20_ARVALID(1'b0), .AXI_20_ARREADY(),
    .AXI_20_RID(), .AXI_20_RDATA(), .AXI_20_RRESP(), .AXI_20_RLAST(),
    .AXI_20_RVALID(), .AXI_20_RREADY(1'b0), .AXI_20_RDATA_PARITY(),

    .AXI_21_ACLK(user_clk), .AXI_21_ARESET_N(1'b0),
    .AXI_21_AWID('0), .AXI_21_AWADDR('0), .AXI_21_AWLEN('0), .AXI_21_AWSIZE('0),
    .AXI_21_AWBURST('0), .AXI_21_AWVALID(1'b0), .AXI_21_AWREADY(),
    .AXI_21_WDATA('0), .AXI_21_WSTRB('0), .AXI_21_WLAST(1'b0), .AXI_21_WVALID(1'b0),
    .AXI_21_WREADY(), .AXI_21_WDATA_PARITY('0),
    .AXI_21_BID(), .AXI_21_BRESP(), .AXI_21_BVALID(), .AXI_21_BREADY(1'b0),
    .AXI_21_ARID('0), .AXI_21_ARADDR('0), .AXI_21_ARLEN('0), .AXI_21_ARSIZE('0),
    .AXI_21_ARBURST('0), .AXI_21_ARVALID(1'b0), .AXI_21_ARREADY(),
    .AXI_21_RID(), .AXI_21_RDATA(), .AXI_21_RRESP(), .AXI_21_RLAST(),
    .AXI_21_RVALID(), .AXI_21_RREADY(1'b0), .AXI_21_RDATA_PARITY(),

    .AXI_22_ACLK(user_clk), .AXI_22_ARESET_N(1'b0),
    .AXI_22_AWID('0), .AXI_22_AWADDR('0), .AXI_22_AWLEN('0), .AXI_22_AWSIZE('0),
    .AXI_22_AWBURST('0), .AXI_22_AWVALID(1'b0), .AXI_22_AWREADY(),
    .AXI_22_WDATA('0), .AXI_22_WSTRB('0), .AXI_22_WLAST(1'b0), .AXI_22_WVALID(1'b0),
    .AXI_22_WREADY(), .AXI_22_WDATA_PARITY('0),
    .AXI_22_BID(), .AXI_22_BRESP(), .AXI_22_BVALID(), .AXI_22_BREADY(1'b0),
    .AXI_22_ARID('0), .AXI_22_ARADDR('0), .AXI_22_ARLEN('0), .AXI_22_ARSIZE('0),
    .AXI_22_ARBURST('0), .AXI_22_ARVALID(1'b0), .AXI_22_ARREADY(),
    .AXI_22_RID(), .AXI_22_RDATA(), .AXI_22_RRESP(), .AXI_22_RLAST(),
    .AXI_22_RVALID(), .AXI_22_RREADY(1'b0), .AXI_22_RDATA_PARITY(),

    .AXI_23_ACLK(user_clk), .AXI_23_ARESET_N(1'b0),
    .AXI_23_AWID('0), .AXI_23_AWADDR('0), .AXI_23_AWLEN('0), .AXI_23_AWSIZE('0),
    .AXI_23_AWBURST('0), .AXI_23_AWVALID(1'b0), .AXI_23_AWREADY(),
    .AXI_23_WDATA('0), .AXI_23_WSTRB('0), .AXI_23_WLAST(1'b0), .AXI_23_WVALID(1'b0),
    .AXI_23_WREADY(), .AXI_23_WDATA_PARITY('0),
    .AXI_23_BID(), .AXI_23_BRESP(), .AXI_23_BVALID(), .AXI_23_BREADY(1'b0),
    .AXI_23_ARID('0), .AXI_23_ARADDR('0), .AXI_23_ARLEN('0), .AXI_23_ARSIZE('0),
    .AXI_23_ARBURST('0), .AXI_23_ARVALID(1'b0), .AXI_23_ARREADY(),
    .AXI_23_RID(), .AXI_23_RDATA(), .AXI_23_RRESP(), .AXI_23_RLAST(),
    .AXI_23_RVALID(), .AXI_23_RREADY(1'b0), .AXI_23_RDATA_PARITY(),

    .AXI_24_ACLK(user_clk), .AXI_24_ARESET_N(1'b0),
    .AXI_24_AWID('0), .AXI_24_AWADDR('0), .AXI_24_AWLEN('0), .AXI_24_AWSIZE('0),
    .AXI_24_AWBURST('0), .AXI_24_AWVALID(1'b0), .AXI_24_AWREADY(),
    .AXI_24_WDATA('0), .AXI_24_WSTRB('0), .AXI_24_WLAST(1'b0), .AXI_24_WVALID(1'b0),
    .AXI_24_WREADY(), .AXI_24_WDATA_PARITY('0),
    .AXI_24_BID(), .AXI_24_BRESP(), .AXI_24_BVALID(), .AXI_24_BREADY(1'b0),
    .AXI_24_ARID('0), .AXI_24_ARADDR('0), .AXI_24_ARLEN('0), .AXI_24_ARSIZE('0),
    .AXI_24_ARBURST('0), .AXI_24_ARVALID(1'b0), .AXI_24_ARREADY(),
    .AXI_24_RID(), .AXI_24_RDATA(), .AXI_24_RRESP(), .AXI_24_RLAST(),
    .AXI_24_RVALID(), .AXI_24_RREADY(1'b0), .AXI_24_RDATA_PARITY(),

    .AXI_25_ACLK(user_clk), .AXI_25_ARESET_N(1'b0),
    .AXI_25_AWID('0), .AXI_25_AWADDR('0), .AXI_25_AWLEN('0), .AXI_25_AWSIZE('0),
    .AXI_25_AWBURST('0), .AXI_25_AWVALID(1'b0), .AXI_25_AWREADY(),
    .AXI_25_WDATA('0), .AXI_25_WSTRB('0), .AXI_25_WLAST(1'b0), .AXI_25_WVALID(1'b0),
    .AXI_25_WREADY(), .AXI_25_WDATA_PARITY('0),
    .AXI_25_BID(), .AXI_25_BRESP(), .AXI_25_BVALID(), .AXI_25_BREADY(1'b0),
    .AXI_25_ARID('0), .AXI_25_ARADDR('0), .AXI_25_ARLEN('0), .AXI_25_ARSIZE('0),
    .AXI_25_ARBURST('0), .AXI_25_ARVALID(1'b0), .AXI_25_ARREADY(),
    .AXI_25_RID(), .AXI_25_RDATA(), .AXI_25_RRESP(), .AXI_25_RLAST(),
    .AXI_25_RVALID(), .AXI_25_RREADY(1'b0), .AXI_25_RDATA_PARITY(),

    .AXI_26_ACLK(user_clk), .AXI_26_ARESET_N(1'b0),
    .AXI_26_AWID('0), .AXI_26_AWADDR('0), .AXI_26_AWLEN('0), .AXI_26_AWSIZE('0),
    .AXI_26_AWBURST('0), .AXI_26_AWVALID(1'b0), .AXI_26_AWREADY(),
    .AXI_26_WDATA('0), .AXI_26_WSTRB('0), .AXI_26_WLAST(1'b0), .AXI_26_WVALID(1'b0),
    .AXI_26_WREADY(), .AXI_26_WDATA_PARITY('0),
    .AXI_26_BID(), .AXI_26_BRESP(), .AXI_26_BVALID(), .AXI_26_BREADY(1'b0),
    .AXI_26_ARID('0), .AXI_26_ARADDR('0), .AXI_26_ARLEN('0), .AXI_26_ARSIZE('0),
    .AXI_26_ARBURST('0), .AXI_26_ARVALID(1'b0), .AXI_26_ARREADY(),
    .AXI_26_RID(), .AXI_26_RDATA(), .AXI_26_RRESP(), .AXI_26_RLAST(),
    .AXI_26_RVALID(), .AXI_26_RREADY(1'b0), .AXI_26_RDATA_PARITY(),

    .AXI_27_ACLK(user_clk), .AXI_27_ARESET_N(1'b0),
    .AXI_27_AWID('0), .AXI_27_AWADDR('0), .AXI_27_AWLEN('0), .AXI_27_AWSIZE('0),
    .AXI_27_AWBURST('0), .AXI_27_AWVALID(1'b0), .AXI_27_AWREADY(),
    .AXI_27_WDATA('0), .AXI_27_WSTRB('0), .AXI_27_WLAST(1'b0), .AXI_27_WVALID(1'b0),
    .AXI_27_WREADY(), .AXI_27_WDATA_PARITY('0),
    .AXI_27_BID(), .AXI_27_BRESP(), .AXI_27_BVALID(), .AXI_27_BREADY(1'b0),
    .AXI_27_ARID('0), .AXI_27_ARADDR('0), .AXI_27_ARLEN('0), .AXI_27_ARSIZE('0),
    .AXI_27_ARBURST('0), .AXI_27_ARVALID(1'b0), .AXI_27_ARREADY(),
    .AXI_27_RID(), .AXI_27_RDATA(), .AXI_27_RRESP(), .AXI_27_RLAST(),
    .AXI_27_RVALID(), .AXI_27_RREADY(1'b0), .AXI_27_RDATA_PARITY(),

    .AXI_28_ACLK(user_clk), .AXI_28_ARESET_N(1'b0),
    .AXI_28_AWID('0), .AXI_28_AWADDR('0), .AXI_28_AWLEN('0), .AXI_28_AWSIZE('0),
    .AXI_28_AWBURST('0), .AXI_28_AWVALID(1'b0), .AXI_28_AWREADY(),
    .AXI_28_WDATA('0), .AXI_28_WSTRB('0), .AXI_28_WLAST(1'b0), .AXI_28_WVALID(1'b0),
    .AXI_28_WREADY(), .AXI_28_WDATA_PARITY('0),
    .AXI_28_BID(), .AXI_28_BRESP(), .AXI_28_BVALID(), .AXI_28_BREADY(1'b0),
    .AXI_28_ARID('0), .AXI_28_ARADDR('0), .AXI_28_ARLEN('0), .AXI_28_ARSIZE('0),
    .AXI_28_ARBURST('0), .AXI_28_ARVALID(1'b0), .AXI_28_ARREADY(),
    .AXI_28_RID(), .AXI_28_RDATA(), .AXI_28_RRESP(), .AXI_28_RLAST(),
    .AXI_28_RVALID(), .AXI_28_RREADY(1'b0), .AXI_28_RDATA_PARITY(),

    .AXI_29_ACLK(user_clk), .AXI_29_ARESET_N(1'b0),
    .AXI_29_AWID('0), .AXI_29_AWADDR('0), .AXI_29_AWLEN('0), .AXI_29_AWSIZE('0),
    .AXI_29_AWBURST('0), .AXI_29_AWVALID(1'b0), .AXI_29_AWREADY(),
    .AXI_29_WDATA('0), .AXI_29_WSTRB('0), .AXI_29_WLAST(1'b0), .AXI_29_WVALID(1'b0),
    .AXI_29_WREADY(), .AXI_29_WDATA_PARITY('0),
    .AXI_29_BID(), .AXI_29_BRESP(), .AXI_29_BVALID(), .AXI_29_BREADY(1'b0),
    .AXI_29_ARID('0), .AXI_29_ARADDR('0), .AXI_29_ARLEN('0), .AXI_29_ARSIZE('0),
    .AXI_29_ARBURST('0), .AXI_29_ARVALID(1'b0), .AXI_29_ARREADY(),
    .AXI_29_RID(), .AXI_29_RDATA(), .AXI_29_RRESP(), .AXI_29_RLAST(),
    .AXI_29_RVALID(), .AXI_29_RREADY(1'b0), .AXI_29_RDATA_PARITY(),

    .AXI_30_ACLK(user_clk), .AXI_30_ARESET_N(1'b0),
    .AXI_30_AWID('0), .AXI_30_AWADDR('0), .AXI_30_AWLEN('0), .AXI_30_AWSIZE('0),
    .AXI_30_AWBURST('0), .AXI_30_AWVALID(1'b0), .AXI_30_AWREADY(),
    .AXI_30_WDATA('0), .AXI_30_WSTRB('0), .AXI_30_WLAST(1'b0), .AXI_30_WVALID(1'b0),
    .AXI_30_WREADY(), .AXI_30_WDATA_PARITY('0),
    .AXI_30_BID(), .AXI_30_BRESP(), .AXI_30_BVALID(), .AXI_30_BREADY(1'b0),
    .AXI_30_ARID('0), .AXI_30_ARADDR('0), .AXI_30_ARLEN('0), .AXI_30_ARSIZE('0),
    .AXI_30_ARBURST('0), .AXI_30_ARVALID(1'b0), .AXI_30_ARREADY(),
    .AXI_30_RID(), .AXI_30_RDATA(), .AXI_30_RRESP(), .AXI_30_RLAST(),
    .AXI_30_RVALID(), .AXI_30_RREADY(1'b0), .AXI_30_RDATA_PARITY(),

    .AXI_31_ACLK(user_clk), .AXI_31_ARESET_N(1'b0),
    .AXI_31_AWID('0), .AXI_31_AWADDR('0), .AXI_31_AWLEN('0), .AXI_31_AWSIZE('0),
    .AXI_31_AWBURST('0), .AXI_31_AWVALID(1'b0), .AXI_31_AWREADY(),
    .AXI_31_WDATA('0), .AXI_31_WSTRB('0), .AXI_31_WLAST(1'b0), .AXI_31_WVALID(1'b0),
    .AXI_31_WREADY(), .AXI_31_WDATA_PARITY('0),
    .AXI_31_BID(), .AXI_31_BRESP(), .AXI_31_BVALID(), .AXI_31_BREADY(1'b0),
    .AXI_31_ARID('0), .AXI_31_ARADDR('0), .AXI_31_ARLEN('0), .AXI_31_ARSIZE('0),
    .AXI_31_ARBURST('0), .AXI_31_ARVALID(1'b0), .AXI_31_ARREADY(),
    .AXI_31_RID(), .AXI_31_RDATA(), .AXI_31_RRESP(), .AXI_31_RLAST(),
    .AXI_31_RVALID(), .AXI_31_RREADY(1'b0), .AXI_31_RDATA_PARITY(),

    // Calibration complete
    .apb_complete_0    (apb_complete_0),
    .apb_complete_1    (apb_complete_1),

    // Temperature / catastrophic trip (not used in M1 shell)
    .DRAM_0_STAT_CATTRIP(),
    .DRAM_0_STAT_TEMP  (),
    .DRAM_1_STAT_CATTRIP(),
    .DRAM_1_STAT_TEMP  ()
  );
  /* verilator lint_on PINCONNECTEMPTY */

/* verilator lint_on UNUSEDSIGNAL */
endmodule
