"""Phase A — pick 100 symbols with peak_open_orders ≤ 50, top-100 by msg count.

Falls back to peak ≤ 80 then ≤ 120 if the primary filter yields < 100 hits.
Emits lob_core_sym_pkg.sv (STOCK_LOCATE_TO_SYM_IDX[8192], INITIAL_MIDPRICE[N]),
lob_core_sym_init.mem ($readmemh format), and docs/m06/symbol_selection.md.

Spec: docs/superpowers/specs/2026-05-12-nanobook-m06-multi-symbol-sliding-window-design.md
  §5.1 selection methodology, §3.6 sym_idx_lut init format.
"""
from __future__ import annotations

import argparse
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path


N_SYMBOLS_DEFAULT = 100
SYM_LUT_DEPTH = 8192       # ITCH stock_locate range
SPAN_MAX_DEFAULT = 4096 * 8  # 32K-tick price span — allows ~7 rebases per symbol


@dataclass(frozen=True)
class Candidate:
    stock_locate: int
    msg_count: int
    peak_open_orders: int
    price_span_ticks: int
    has_a: bool
    has_d: bool
    first_add_price: int


def _filter(cands: Iterable[Candidate], peak_max: int, span_max: int) -> list[Candidate]:
    return [
        c for c in cands
        if c.peak_open_orders <= peak_max
        and c.price_span_ticks <= span_max
        and c.has_a and c.has_d
    ]


def select_symbols(
    cands: Iterable[Candidate],
    *, n_symbols: int = N_SYMBOLS_DEFAULT,
    peak_max: int = 50,
    span_max: int = SPAN_MAX_DEFAULT,
) -> tuple[list[Candidate], str]:
    """Filter + sort + take top-N. Returns (picked, fallback_tag)."""
    cands = list(cands)
    for tag, peak in (("primary", peak_max), ("peak_80", 80), ("peak_120", 120)):
        survivors = _filter(cands, peak, span_max)
        if len(survivors) >= n_symbols:
            survivors.sort(key=lambda c: c.msg_count, reverse=True)
            return survivors[:n_symbols], tag
    raise ValueError(
        f"exhausted fallback ladder (primary={peak_max}, then 80, then 120); "
        f"insufficient candidates in slice"
    )


def aggregate_from_events(path: Path) -> list[Candidate]:
    """Stream events and aggregate per-stock_locate stats. Returns Candidate list.

    Filters out symbols whose `stock_locate` exceeds `SYM_LUT_DEPTH` — those
    can't fit in the M06 sym_idx_lut (8K-entry distRAM, design §3.6) and are
    typically inactive symbols anyway. M07's HBM-backed sym_idx_lut lifts
    this cap.
    """
    from sw.m05_tools.symbol_stats import compute_symbol_stats
    stats = compute_symbol_stats(path)
    out: list[Candidate] = []
    for loc, s in stats.items():
        if loc >= SYM_LUT_DEPTH:
            continue
        if s.price_min is None or s.price_max is None:
            continue
        out.append(Candidate(
            stock_locate=loc, msg_count=s.msg_count,
            peak_open_orders=s.peak_open_orders,
            price_span_ticks=int(s.price_max - s.price_min),
            has_a=s.type_counts.get("A", 0) > 0,
            has_d=s.type_counts.get("D", 0) > 0,
            first_add_price=int(s.price_min),
        ))
    return out


def format_sv_pkg(picked: list[Candidate]) -> str:
    n_used = len(picked)
    # Build 8192-entry LUT: { valid[7], sym_idx[6:0] }
    lut = [0] * SYM_LUT_DEPTH
    for sym_idx, c in enumerate(picked):
        if c.stock_locate >= SYM_LUT_DEPTH:
            raise ValueError(f"stock_locate {c.stock_locate} >= {SYM_LUT_DEPTH}")
        lut[c.stock_locate] = 0x80 | (sym_idx & 0x7F)
    lut_lines = []
    for v in lut:
        lut_lines.append(f"    8'h{v:02x}")
    lut_body = ",\n".join(lut_lines)

    mid_lines = []
    for c in picked:
        mid_lines.append(f"    32'd{c.first_add_price}")
    mid_body = ",\n".join(mid_lines)

    return f"""// Auto-generated by sw/m06_tools/pick_symbols.py — do not edit by hand.
// Source: docs/m06/symbol_selection.md
package lob_core_sym_pkg;

  parameter int unsigned SYM_LUT_DEPTH    = {SYM_LUT_DEPTH};
  parameter int unsigned N_SYMBOLS_USED   = {n_used};

  // stock_locate → {{ valid[7], sym_idx[6:0] }}. valid = MSB.
  parameter logic [7:0] STOCK_LOCATE_TO_SYM_IDX [{SYM_LUT_DEPTH}] = '{{
{lut_body}
  }};

  // First-observed ADD price per sym_idx; used to seed per_sym_state.midprice.
  parameter logic [31:0] INITIAL_MIDPRICE [{n_used}] = '{{
{mid_body}
  }};

endpackage : lob_core_sym_pkg
"""


def format_init_mem(picked: list[Candidate]) -> str:
    """`$readmemh` format — one byte per line, 8192 lines."""
    lut = [0] * SYM_LUT_DEPTH
    for sym_idx, c in enumerate(picked):
        lut[c.stock_locate] = 0x80 | (sym_idx & 0x7F)
    return "\n".join(f"{v:02x}" for v in lut) + "\n"


def format_selection_md(picked: list[Candidate], fallback: str) -> str:
    rows = [
        "| sym_idx | stock_locate | msg_count | peak_open | price_span | first_add_price |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for i, c in enumerate(picked):
        rows.append(
            f"| {i} | {c.stock_locate} | {c.msg_count} | {c.peak_open_orders} "
            f"| {c.price_span_ticks} | {c.first_add_price} |"
        )
    table = "\n".join(rows)
    return f"""# M06 Phase A — Symbol selection report

Fallback tier: **{fallback}**
Selected: **{len(picked)}** symbols

{table}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--events", type=Path, required=True,
                    help="Path to .events.bin from M04 slice")
    ap.add_argument("--peak-max", type=int, default=50)
    ap.add_argument("--n-symbols", type=int, default=N_SYMBOLS_DEFAULT)
    ap.add_argument("--sv-out", type=Path,
                    default=Path("hw/ip/lob_core/lob_core_sym_pkg.sv"))
    ap.add_argument("--mem-out", type=Path,
                    default=Path("hw/ip/lob_core/lob_core_sym_init.mem"))
    ap.add_argument("--md-out", type=Path,
                    default=Path("docs/m06/symbol_selection.md"))
    args = ap.parse_args()

    cands = aggregate_from_events(args.events)
    picked, fallback = select_symbols(
        cands, n_symbols=args.n_symbols, peak_max=args.peak_max,
    )

    args.sv_out.parent.mkdir(parents=True, exist_ok=True)
    args.mem_out.parent.mkdir(parents=True, exist_ok=True)
    args.md_out.parent.mkdir(parents=True, exist_ok=True)
    args.sv_out.write_text(format_sv_pkg(picked))
    args.mem_out.write_text(format_init_mem(picked))
    args.md_out.write_text(format_selection_md(picked, fallback))

    print(f"selected {len(picked)} symbols (fallback={fallback})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
