// Auto-generated by sw/m05_tools/pick_params.py — do not edit by hand.
// Source: docs/m05/symbol_selection.md + docs/m05/hash_sizing.md
package lob_core_params_pkg;

  // Phase B selection
  parameter int unsigned SYMBOL_FILTER_ID  = 5754;
  parameter int unsigned WINDOW_BASE_TICK  = 354000;
  parameter int unsigned WINDOW_SIZE_TICKS = 4096;
  parameter int unsigned POOL_SLOTS        = 8192;
  parameter int unsigned HASH_SLOTS        = 65536;
  parameter int unsigned MAX_PROBE_DEPTH   = 4;

  typedef enum logic [1:0] {
    HASH_XORSHIFT64 = 2'd0,
    HASH_CRC32      = 2'd1,
    HASH_FIBONACCI  = 2'd2
  } hash_fn_e;

  parameter hash_fn_e HASH_FN = HASH_XORSHIFT64;

endpackage : lob_core_params_pkg
