// Auto-generated by sw/m06_tools/pick_symbols.py — do not edit by hand.
// Source: docs/m06/symbol_selection.md + docs/m06/sizing_review.md
package lob_core_params_pkg;

  // ---- M06 multi-symbol parameters ----
  // M05 consumers don't reference these yet — silence Verilator UNUSEDPARAM
  // until Phase B/C/D wire them up.
  /* verilator lint_off UNUSEDPARAM */
  parameter int unsigned N_SYMBOLS         = 128;     // power of 2; 100 used, 28 reserved
  parameter int unsigned SYM_IDX_W         = 7;       // $clog2(N_SYMBOLS)
  parameter int unsigned EPOCH_W           = 16;      // see spec §3.5
  parameter int unsigned WINDOW_HALF_TICKS = 2048;    // refbook FROZEN
  parameter int unsigned WINDOW_SIZE_TICKS = 4096;
  parameter int unsigned EMA_SHIFT         = 4;       // α = 1/16
  parameter int unsigned CLZ_LATENCY       = 1;       // baseline; bump to 2 if Phase J flags
  /* verilator lint_on UNUSEDPARAM */

  // ---- Pool/hash sizing (M06 Phase A sizing review) ----
  // POOL_SLOTS bumped from 16384 → 32768 because residual leak estimate from
  // data/golden/2019-03-27.events.bin was 10586 (> 0.5 × 16384 = 8192).
  // See docs/m06/sizing_review.md.
  parameter int unsigned POOL_SLOTS        = 32768;
  parameter int unsigned HASH_SLOTS        = 32768;
  parameter int unsigned MAX_PROBE_DEPTH   = 4;

  // ---- M05 carry-over: still consumed by tob_tracker.sv as parameter defaults.
  //      Phase C/D removes these consumers; until then they remain as
  //      backward-compat stubs so M05 unit TBs continue to pass.
  parameter int unsigned SYMBOL_FILTER_ID  = 5754;
  parameter int unsigned WINDOW_BASE_TICK  = 354000;

  typedef enum logic [1:0] {
    HASH_XORSHIFT64 = 2'd0,
    HASH_CRC32      = 2'd1,
    HASH_FIBONACCI  = 2'd2
  } hash_fn_e;

  parameter hash_fn_e HASH_FN = HASH_XORSHIFT64;

endpackage : lob_core_params_pkg
