// SPDX-License-Identifier: Apache-2.0
// sym_idx_lut — combinational distRAM lookup from ITCH stock_locate to
// { valid, sym_idx[6:0] }. M06 only — M07 migrates to HBM-backed.
//
// Spec: docs/design.md §3.6 (combinational distRAM, ~2K LUT cost, no
// pipeline cycle).
// Plan: docs/superpowers/plans/2026-05-12-nanobook-m06-multi-symbol-sliding-window.md
//       Task E.1.
//
// Init data comes from lob_core_sym_pkg::STOCK_LOCATE_TO_SYM_IDX, an 8192
// entry × 8-bit parameter array auto-generated by sw/m06_tools/pick_symbols.py
// from the M04 day's top-100 symbols. Each entry encodes
// { valid[7], sym_idx[6:0] }. valid=0 means "this stock_locate is not one of
// the picked symbols → silently drop". Using the package parameter (instead
// of $readmemh on the .mem sibling file) keeps sim and synth in lock-step
// without a runtime file-search dependency.

// Module-level parameter SYM_LUT_DEPTH deliberately shadows the imported
// package symbol so that parameter overrides at instantiation work; the
// VARHIDDEN waiver covers the shadow.
/* verilator lint_off UNUSEDPARAM */
/* verilator lint_off VARHIDDEN */
module sym_idx_lut
  import lob_core_sym_pkg::*;
#(
    parameter int unsigned SYM_LUT_DEPTH = lob_core_sym_pkg::SYM_LUT_DEPTH,
    parameter int unsigned SYM_IDX_W     = lob_core_params_pkg::SYM_IDX_W
) (
    input  logic [$clog2(SYM_LUT_DEPTH)-1:0] stock_locate,
    output logic                              valid_o,
    output logic [SYM_IDX_W-1:0]              sym_idx_o
);
/* verilator lint_on VARHIDDEN */
/* verilator lint_on UNUSEDPARAM */
    // Sibling-package parameter touch — lob_core_params_pkg / lob_core_sym_pkg
    // are mostly consumed by sibling modules (tob_tracker, price_ladder,
    // per_sym_state). sym_idx_lut only needs SYM_IDX_W and SYM_LUT_DEPTH;
    // touching the rest as localparams keeps the standalone lint clean.
    /* verilator lint_off UNUSEDPARAM */
    localparam int unsigned _PKG_WINDOW_BASE_TICK   =
        lob_core_params_pkg::WINDOW_BASE_TICK;
    localparam int unsigned _PKG_WINDOW_SIZE_TICKS  =
        lob_core_params_pkg::WINDOW_SIZE_TICKS;
    localparam int unsigned _PKG_SYMBOL_FILTER_ID   =
        lob_core_params_pkg::SYMBOL_FILTER_ID;
    localparam int unsigned _PKG_POOL_SLOTS         =
        lob_core_params_pkg::POOL_SLOTS;
    localparam int unsigned _PKG_HASH_SLOTS         =
        lob_core_params_pkg::HASH_SLOTS;
    localparam int unsigned _PKG_MAX_PROBE_DEPTH    =
        lob_core_params_pkg::MAX_PROBE_DEPTH;
    localparam lob_core_params_pkg::hash_fn_e _PKG_HASH_FN =
        lob_core_params_pkg::HASH_FN;
    localparam int unsigned _PKG_N_SYMBOLS_USED     =
        lob_core_sym_pkg::N_SYMBOLS_USED;
    localparam logic [31:0] _PKG_INITIAL_MIDPRICE_0 =
        lob_core_sym_pkg::INITIAL_MIDPRICE[0];
    /* verilator lint_on UNUSEDPARAM */

    // 8K × 8b distRAM. RAM_STYLE distributed forces LUTRAM inference.
    // Initial-block copy from the package keeps the array a `logic` (not a
    // `const`) so Vivado infers writeable distRAM rather than a ROM macro.
    (* ram_style = "distributed" *)
    logic [7:0] lut [SYM_LUT_DEPTH];

    initial begin
        for (int i = 0; i < SYM_LUT_DEPTH; i++) begin
            lut[i] = STOCK_LOCATE_TO_SYM_IDX[i];
        end
    end

    logic [7:0] entry;
    assign entry     = lut[stock_locate];
    assign valid_o   = entry[7];
    assign sym_idx_o = entry[SYM_IDX_W-1:0];

endmodule : sym_idx_lut
