TOPLEVEL := extract_cancel
MODULE   := tb_extract_cancel
VERILOG_SOURCES := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/itch_decoder/book_event_pkg.sv) \
                   $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/itch_decoder/extract_cancel.sv)
include $(dir $(lastword $(MAKEFILE_LIST)))Makefile
