TOPLEVEL        := mold_strip
MODULE          := tb_mold_strip
VERILOG_SOURCES := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/itch_decoder/book_event_pkg.sv) \
                   $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/itch_decoder/mold_strip.sv)
include $(dir $(lastword $(MAKEFILE_LIST)))Makefile
