TOPLEVEL := extract_delete
MODULE   := tb_extract_delete
VERILOG_SOURCES := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/itch_decoder/book_event_pkg.sv) \
                   $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/itch_decoder/extract_delete.sv)
include $(dir $(lastword $(MAKEFILE_LIST)))Makefile
