TOPLEVEL := type_dispatch
MODULE   := tb_type_dispatch
VERILOG_SOURCES := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/itch_decoder/book_event_pkg.sv) \
                   $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/itch_decoder/type_dispatch.sv)
include $(dir $(lastword $(MAKEFILE_LIST)))Makefile
