"""Emit the chosen M05 parameters as a SystemVerilog package + JSON sidecar.

The package is the single source of truth used by lob_core.sv and all TBs
to size POOL_SLOTS / HASH_SLOTS / WINDOW_BASE_TICK / SYMBOL_FILTER_ID. Phase B
runs this script after symbol_stats + hash_sim; the package is committed.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


_HASH_FN_TO_RTL = {
    "xorshift64":   "HASH_XORSHIFT64",
    "crc32_low64":  "HASH_CRC32",
    "fibonacci_mul": "HASH_FIBONACCI",
}


def _next_pow2(x: int) -> int:
    p = 1
    while p < x:
        p <<= 1
    return p


def emit_sv(symbol_id: int, peak_open: int, price_min: int,
            window_size: int, hash_fn: str, hash_slots: int,
            pool_slots: int) -> str:
    base_tick = (price_min // 1000) * 1000
    if hash_fn not in _HASH_FN_TO_RTL:
        raise ValueError(f"unknown hash function: {hash_fn}")
    return f"""// Auto-generated by sw/m05_tools/pick_params.py — do not edit by hand.
// Source: docs/m05/symbol_selection.md + docs/m05/hash_sizing.md
package lob_core_params_pkg;

  // Phase B selection
  parameter int unsigned SYMBOL_FILTER_ID  = {symbol_id};
  parameter int unsigned WINDOW_BASE_TICK  = {base_tick};
  parameter int unsigned WINDOW_SIZE_TICKS = {window_size};
  parameter int unsigned POOL_SLOTS        = {pool_slots};
  parameter int unsigned HASH_SLOTS        = {hash_slots};
  parameter int unsigned MAX_PROBE_DEPTH   = 4;

  typedef enum logic [1:0] {{
    HASH_XORSHIFT64 = 2'd0,
    HASH_CRC32      = 2'd1,
    HASH_FIBONACCI  = 2'd2
  }} hash_fn_e;

  parameter hash_fn_e HASH_FN = {_HASH_FN_TO_RTL[hash_fn]};

endpackage : lob_core_params_pkg
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--symbol", type=int, required=True)
    ap.add_argument("--peak-open", type=int, required=True,
                    help="Peak simultaneously-open orders on chosen symbol (Phase B Task 6)")
    ap.add_argument("--price-min", type=int, required=True)
    ap.add_argument("--window-size", type=int, default=4096)
    ap.add_argument("--hash-fn", choices=list(_HASH_FN_TO_RTL.keys()), required=True)
    ap.add_argument("--hash-slots", type=int, required=True)
    ap.add_argument("--pool-slots", type=int, default=None,
                    help="Override POOL_SLOTS. Default: next_pow2(peak_open * 1.5). Override "
                         "with a larger value to keep URAM utilisation in the spec §5.1 band "
                         "when the chosen symbol is lightly traded.")
    ap.add_argument("--sv-out", type=Path, default=Path("hw/ip/lob_core/lob_core_params_pkg.sv"))
    ap.add_argument("--json-out", type=Path, default=Path("docs/m05/params.json"))
    args = ap.parse_args()

    pool_slots = args.pool_slots if args.pool_slots is not None \
        else _next_pow2(int(args.peak_open * 1.5))

    sv = emit_sv(
        args.symbol, args.peak_open, args.price_min,
        args.window_size, args.hash_fn, args.hash_slots, pool_slots,
    )
    args.sv_out.parent.mkdir(parents=True, exist_ok=True)
    args.sv_out.write_text(sv)
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps({
        "symbol_id": args.symbol,
        "peak_open": args.peak_open,
        "price_min": args.price_min,
        "window_size": args.window_size,
        "hash_fn": args.hash_fn,
        "hash_slots": args.hash_slots,
        "pool_slots": pool_slots,
        "window_base_tick": (args.price_min // 1000) * 1000,
    }, indent=2) + "\n")
    print(f"wrote {args.sv_out} and {args.json_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
