# synth.tcl — In-process Vivado build script for nanobook U50 shell
# Usage: vivado -mode batch -source synth.tcl -tclargs [TOP]
# Uses in-process flow (synth_design/place_design/route_design) — NOT launch_runs.

# ---------------------------------------------------------------------------
# Parameters
# ---------------------------------------------------------------------------
set TOP     [lindex $argv 0]
if {$TOP eq ""} { set TOP "nanobook_shell_top" }

set PART    "xcu50-fsvh2104-2-e"
set OUT_DIR "build/vivado"

# ---------------------------------------------------------------------------
# Capture HEAD SHA → build_sha.vh
# ---------------------------------------------------------------------------
set SHA_HEX [string trim [exec git rev-parse HEAD]]
set LO_HEX  [string range $SHA_HEX 0 7]
set HI_HEX  [string range $SHA_HEX 8 15]

set f [open build_sha.vh w]
puts $f "// Auto-generated by synth.tcl — DO NOT EDIT"
puts $f "`define BUILD_SHA_LO 32'h${LO_HEX}"
puts $f "`define BUILD_SHA_HI 32'h${HI_HEX}"
close $f

puts "INFO: build_sha.vh written (SHA ${SHA_HEX})"

# ---------------------------------------------------------------------------
# Project setup (in-memory — no .xpr written)
# ---------------------------------------------------------------------------
file mkdir $OUT_DIR

create_project -in_memory -part $PART

set_property target_language SystemVerilog [current_project]

# ---------------------------------------------------------------------------
# Add RTL sources
# ---------------------------------------------------------------------------
foreach src [concat \
    [glob -nocomplain ../ip/xdma_wrapper/*.sv] \
    [glob -nocomplain ../ip/hbm_wrapper/*.sv]  \
    [glob -nocomplain ../ip/eth10g_wrapper/*.sv] \
    [list "../top/${TOP}.sv"] \
] {
    read_verilog -sv $src
}

# Include build_sha.vh in the include path
set_property include_dirs [list [pwd]] [current_fileset]

# ---------------------------------------------------------------------------
# Add IPs
# ---------------------------------------------------------------------------
foreach xci [glob -nocomplain ../ip/*/ip/*.xci] {
    read_ip $xci
}

# ---------------------------------------------------------------------------
# Constraints
# ---------------------------------------------------------------------------
read_xdc u50.xdc

# ---------------------------------------------------------------------------
# Synthesis
# ---------------------------------------------------------------------------
puts "INFO: Running synth_design -top ${TOP} -part ${PART}"
synth_design -top $TOP -part $PART -flatten_hierarchy rebuilt

write_checkpoint -force ${OUT_DIR}/post_synth.dcp

report_utilization   -file ${OUT_DIR}/post_synth_util.rpt
report_timing_summary -file ${OUT_DIR}/post_synth_timing.rpt \
    -max_paths 10 -warn_on_violation

# ---------------------------------------------------------------------------
# Implementation
# ---------------------------------------------------------------------------
puts "INFO: Running opt_design"
opt_design

puts "INFO: Running place_design"
place_design

puts "INFO: Running route_design"
route_design

write_checkpoint -force ${OUT_DIR}/post_route.dcp

report_utilization   -file ${OUT_DIR}/impl_util.rpt
report_timing_summary -file ${OUT_DIR}/impl_timing.rpt \
    -max_paths 10 -warn_on_violation
report_drc           -file ${OUT_DIR}/impl_drc.rpt

# ---------------------------------------------------------------------------
# Outputs
# ---------------------------------------------------------------------------
write_bitstream  -force ${OUT_DIR}/${TOP}.bit
write_debug_probes -force ${OUT_DIR}/${TOP}.ltx

puts "INFO: Build complete — bitstream at ${OUT_DIR}/${TOP}.bit"
