// Month 1 shell top: XDMA + HBM + 10G + GPIO. No decoder, no book.
// build_sha.vh is generated by hw/synth/Makefile at synthesis time.
// The ifndef guard provides safe defaults for simulation.
`ifndef BUILD_SHA_LO
`define BUILD_SHA_LO 32'h0
`define BUILD_SHA_HI 32'h0
`endif
`timescale 1ns/1ps
/* verilator lint_off UNUSEDSIGNAL */
module nanobook_shell_top (
  // PCIe
  input  wire         pcie_refclk_p,
  input  wire         pcie_refclk_n,
  input  wire         pcie_rstn,
  input  wire  [3:0]  pcie_rx_p,
  input  wire  [3:0]  pcie_rx_n,
  output wire  [3:0]  pcie_tx_p,
  output wire  [3:0]  pcie_tx_n,
  // HBM reference clock
  input  wire         hbm_refclk_p,
  input  wire         hbm_refclk_n,
  // QSFP28 lane 0 (10G single-lane)
  input  wire         qsfp0_refclk_p,
  input  wire         qsfp0_refclk_n,
  input  wire         qsfp0_rx_p,
  input  wire         qsfp0_rx_n,
  output wire         qsfp0_tx_p,
  output wire         qsfp0_tx_n,
  // GPIO (U50 exposes 3 LEDs: act=E18, stat_g=E16, stat_y=F17)
  output wire  [2:0]  gpio_led,
  // HBM catastrophic over-temperature output (J18) — must be driven; tie low
  output wire         hbm_cattrip
);

  // -------------------------------------------------------------------------
  // User-domain clock and reset (driven by xdma_wrapper; used by future IPs)
  // -------------------------------------------------------------------------
  logic user_clk;
  logic user_rstn;

  // -------------------------------------------------------------------------
  // Control / status wires from xdma_wrapper
  // -------------------------------------------------------------------------
  logic [2:0] control;    // lint_off: consumed by future pipeline modules
  logic [3:0] gpio_led_int;  // BAR0 drives 4 bits; top only forwards [2:0] to 3 physical LEDs

  // 10G status
  logic eth10g_ready_sig;

  // HBM smoke-test control/status wires
  logic hbm_smoke_go;
  logic hbm_smoke_done;
  logic hbm_smoke_any_error;
  logic hbm_ready_sig;

  // -------------------------------------------------------------------------
  // XDMA wrapper (XDMA IP + BAR0 register file)
  // -------------------------------------------------------------------------
  xdma_wrapper u_xdma_wrapper (
    .pcie_refclk_p    (pcie_refclk_p),
    .pcie_refclk_n    (pcie_refclk_n),
    .pcie_rstn        (pcie_rstn),
    .pcie_rx_p        (pcie_rx_p),
    .pcie_rx_n        (pcie_rx_n),
    .pcie_tx_p        (pcie_tx_p),
    .pcie_tx_n        (pcie_tx_n),
    .user_clk         (user_clk),
    .user_rstn        (user_rstn),
    .hbm_ready_i      (hbm_ready_sig),
    .eth10g_ready_i   (eth10g_ready_sig),
    .hbm_done_i       (hbm_smoke_done),
    .hbm_any_error_i  (hbm_smoke_any_error),
    .git_sha_lo_i     (`BUILD_SHA_LO),
    .git_sha_hi_i     (`BUILD_SHA_HI),
    .control_o        (control),
    .gpio_led_o       (gpio_led_int),
    .hbm_smoke_go_o   (hbm_smoke_go)
  );

  // -------------------------------------------------------------------------
  // HBM wrapper (HBM IP + traffic generator)
  // -------------------------------------------------------------------------
  hbm_wrapper u_hbm_wrapper (
    .hbm_refclk_p    (hbm_refclk_p),
    .hbm_refclk_n    (hbm_refclk_n),
    .user_clk        (user_clk),
    .user_rstn       (user_rstn),
    .smoke_go        (hbm_smoke_go),
    .smoke_done      (hbm_smoke_done),
    .smoke_any_error (hbm_smoke_any_error),
    .hbm_ready       (hbm_ready_sig)
  );

  // -------------------------------------------------------------------------
  // GPIO LED driven by BAR0 CONTROL[6:3] — only 3 physical LEDs on U50
  // -------------------------------------------------------------------------
  assign gpio_led    = gpio_led_int[2:0];
  assign hbm_cattrip = 1'b0;

  // -------------------------------------------------------------------------
  // QSFP28 refclk: IBUFDS_GTE4 converts differential 156.25 MHz to GT refclk
  // -------------------------------------------------------------------------
  wire qsfp0_refclk_gt;
  wire qsfp0_refclk_se;
  IBUFDS_GTE4 #(
    .REFCLK_HROW_CK_SEL(2'b00)
  ) u_ibufds_qsfp0 (
    .I    (qsfp0_refclk_p),
    .IB   (qsfp0_refclk_n),
    .CEB  (1'b0),
    .O    (qsfp0_refclk_gt),
    .ODIV2(qsfp0_refclk_se)
  );

  // -------------------------------------------------------------------------
  // 10G GTY wrapper + XGMII loopback
  // -------------------------------------------------------------------------
  logic xgmii_tx_clk;
  logic xgmii_tx_rst;
  logic xgmii_rx_clk;
  logic xgmii_rx_rst;
  logic [63:0] xgmii_txd;
  logic  [7:0] xgmii_txc;
  logic [63:0] xgmii_rxd;
  logic  [7:0] xgmii_rxc;

  gty_10g_wrapper u_gty_10g (
    .refclk        (qsfp0_refclk_gt),
    .sys_clk       (user_clk),
    .sys_rstn      (user_rstn),
    .rx_p          (qsfp0_rx_p),
    .rx_n          (qsfp0_rx_n),
    .tx_p          (qsfp0_tx_p),
    .tx_n          (qsfp0_tx_n),
    .xgmii_tx_clk  (xgmii_tx_clk),
    .xgmii_tx_rst  (xgmii_tx_rst),
    .xgmii_txd     (xgmii_txd),
    .xgmii_txc     (xgmii_txc),
    .xgmii_rx_clk  (xgmii_rx_clk),
    .xgmii_rx_rst  (xgmii_rx_rst),
    .xgmii_rxd     (xgmii_rxd),
    .xgmii_rxc     (xgmii_rxc),
    .rx_locked     (eth10g_ready_sig)
  );

  eth10g_loopback u_eth10g_loopback (
    .clk        (xgmii_tx_clk),
    .rst        (xgmii_tx_rst),
    .xgmii_rxd  (xgmii_rxd),
    .xgmii_rxc  (xgmii_rxc),
    .xgmii_txd  (xgmii_txd),
    .xgmii_txc  (xgmii_txc)
  );

endmodule
/* verilator lint_on UNUSEDSIGNAL */
