TOPLEVEL := sym_idx_lut
MODULE   := tb_sym_idx_lut
SIM_BUILD := sim_build_sym_idx_lut

VERILOG_SOURCES := \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/lob_core_params_pkg.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/lob_core_sym_pkg.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/sym_idx_lut.sv)

include $(dir $(lastword $(MAKEFILE_LIST)))Makefile
