TOPLEVEL  := lob_core
MODULE    := tb_lob_core_rebase
SIM_BUILD := sim_build_lob_core_rebase

VERILOG_SOURCES := \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/itch_decoder/book_event_pkg.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/lob_core_params_pkg.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/lob_core_sym_pkg.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/sym_idx_lut.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/per_sym_state.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/order_pool.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/order_id_hash.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/price_ladder.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/tob_tracker.sv) \
    $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../../hw/ip/lob_core/lob_core.sv)

# Same sim-only sizing as Makefile.smoke.
EXTRA_ARGS += -GWINDOW_BASE_TICK=10000 -GWINDOW_SIZE_TICKS=64
EXTRA_ARGS += -GPOOL_SLOTS=64 -GHASH_SLOTS=512

include $(dir $(lastword $(MAKEFILE_LIST)))Makefile
