"""Tests for hw/ip/lob_core/sym_idx_lut.sv.

Plan: docs/superpowers/plans/2026-05-12-nanobook-m06-multi-symbol-sliding-window.md
      Task E.1.
Spec: design.md §3.6 (combinational distRAM, no pipeline cycle).

The sym_idx_lut is a combinational distRAM lookup. The init data comes
from lob_core_sym_pkg::STOCK_LOCATE_TO_SYM_IDX (auto-generated by
sw/m06_tools/pick_symbols.py from the M04 day's top-100 symbols on
2019-03-27). A handful of known-good mappings drawn from that table:

  stock_locate=5754 → sym_idx=0   (AAPL — also the M05 SYMBOL_FILTER_ID)
  stock_locate=3935 → sym_idx=1
  stock_locate=6847 → sym_idx=2
  stock_locate=0    → invalid

If sw/m06_tools/pick_symbols.py is ever re-run against a different day,
these assertions move accordingly.
"""
from __future__ import annotations

import cocotb
from cocotb.triggers import Timer


@cocotb.test()
async def test_lookup_mapped_locate_aapl(dut):
    """stock_locate=5754 maps to sym_idx=0 in the M06 LUT (AAPL)."""
    dut.stock_locate.value = 5754
    await Timer(1, unit="ns")
    assert int(dut.valid_o.value) == 1, (
        f"valid_o={int(dut.valid_o.value)} expected 1 for locate=5754"
    )
    assert int(dut.sym_idx_o.value) == 0, (
        f"sym_idx_o={int(dut.sym_idx_o.value)} expected 0 for locate=5754"
    )


@cocotb.test()
async def test_lookup_mapped_locate_sym1(dut):
    """stock_locate=3935 maps to sym_idx=1 in the M06 LUT."""
    dut.stock_locate.value = 3935
    await Timer(1, unit="ns")
    assert int(dut.valid_o.value) == 1
    assert int(dut.sym_idx_o.value) == 1


@cocotb.test()
async def test_lookup_unmapped_locate_zero(dut):
    """stock_locate=0 is unmapped (init data: 8'h00 = valid bit clear)."""
    dut.stock_locate.value = 0
    await Timer(1, unit="ns")
    assert int(dut.valid_o.value) == 0, (
        f"valid_o={int(dut.valid_o.value)} expected 0 for unmapped locate=0"
    )


@cocotb.test()
async def test_lookup_unmapped_locate_high(dut):
    """A high stock_locate value that's outside the 100 picked symbols."""
    # Pick a locate that we know is unmapped — anything not in the picked
    # set. 4000 should be safely unmapped (only 100 of 8192 entries set).
    dut.stock_locate.value = 4000
    await Timer(1, unit="ns")
    assert int(dut.valid_o.value) == 0


@cocotb.test()
async def test_combinational_no_clock_required(dut):
    """The LUT is combinational (no clk/rstn). Changing stock_locate updates
    valid_o / sym_idx_o without any rising edge."""
    dut.stock_locate.value = 5754
    await Timer(1, unit="ns")
    assert int(dut.valid_o.value) == 1 and int(dut.sym_idx_o.value) == 0
    dut.stock_locate.value = 3935
    await Timer(1, unit="ns")
    assert int(dut.valid_o.value) == 1 and int(dut.sym_idx_o.value) == 1
    dut.stock_locate.value = 0
    await Timer(1, unit="ns")
    assert int(dut.valid_o.value) == 0
